### ISSUE TITLE
How much time did "import generate" take?

### ISSUE THREAD

**Issue by hopeai** [ryankiros/neural-storyteller#23]
I am new to this area. I installed all the dependencies and trying to generate some story for my images and using a nvidia gtx 960M to run. I tried several times to import generate but it took so long I stopped the kernal every time. Could anyone tell me how patient should I be. Or is there anything I am missing.
![imstory](https://cloud.githubusercontent.com/assets/22259298/25490291/1065bb4a-2b75-11e7-8147-ee5fce4938b9.png)

**Comment by LaiDongDong** [comment]
How much memory on your 960M?  my 750+1G is not work, but 1050 and 1080 is working fine.  Or, you can try on Caffe, the load_all() need several hours.

**Comment by hopeai** [comment]
@LaiDongDong 4 GB, I solved the mentioned problem by editing .theanorc.
